---
title: "2.13"
author: "Brandon Short"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)

```

```{r load_data}
# Use this R-Chunk to import all your datasets!
world_data <- read.csv(file = 'food-prices.csv')
head(world_data)
```

## Background

_Place Task Background Here_

## Data Wrangling

```{r tidy_data}
# https://ourworldindata.org/food-prices
worlfil <-world_data%>%
  filter(Entity == 'Nigeria'
         | Entity ==  'Ethiopia'
         | Entity == 'Bangladesh'
         | Entity == 'India'
         | Entity == 'Mexico'
         | Entity == 'Brazil'
         | Entity == 'United States'
         | Entity == 'United Kingdom')%>%
  rename(Health = Healthy.diet.cost.....cannot.afford.)


head(worlfil,8)
```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!
ggplot(data = worlfil)+
  geom_col(aes(x = reorder(Entity, Health), y = Health, fill = Entity))+
  coord_flip() +
  scale_y_continuous(breaks = seq(0,100,20), labels = c("0%","20%","40%","60%","80%",""))+
  theme_classic()+
  scale_fill_manual(values = c( "#279792",
                                "#9A5057",
                                "#BD542D",
                                "#835CA2",
                                "#D62F7D",
                                "#5A697D",
                                "#A1B0C8",
                                "#27955C")) +
  theme(panel.grid.major.x = element_line(linetype = 2))+
  labs(x = "")+
  geom_text( aes(label = round(Health,2), x = Entity, y = Health + 4)) +
  geom_text( aes(label = '%' , x = Entity, y = Health + 9))+
  theme(legend.position = "hidden")
  

```

## Conclusions
