---
title: "3.2"
author: "Brandon Short"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)
library(readr)
```

```{r load_data}
# Use this R-Chunk to import all your datasets!
data<-read_rds("https://github.com/byuistats/data/blob/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.RDS?raw=true") 
```

## Background

_Place Task Background Here_

## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!
view(data)
```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!
ggplot(data = data)+
  geom_point(aes(x = contest_period, y = value, color = variable))+
  theme_classic()+
  labs(x = "1990 - 1998")+
  theme(axis.text.x = element_blank())
  
```

```{r}
# Use this R-Chunk to plot & visualize your data!
newdata<- data%>%
  separate(contest_period, into=c('start_v','end_v'), sep = '-')%>%
  extract(end_v, into=c('end_month', 'end_year'), '(\\D+)(\\d+)', convert=TRUE)%>%
  filter(variable == "DJIA")%>%
  summarise(end_month,end_year,value)%>%
  mutate(end_month = recode(end_month, Dec. = 'December', Febuary = 'February'))
  


pivot_wider(newdata, names_from = end_year, values_from = value)
```

## Conclusions
